### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by owocki** [Developer-piyush/Gitquad#3]
http://857tp1qb31bkh1ncp6f3vsbb0s.ingress.provider-0.prod.ams1.akash.pub/ is down

**Comment by owocki** [comment]
@Developer-piyush any way to fix this?  cc @ Kweiss

**Comment by Developer-piyush** [comment]
The lease is expired: Please replace pinged link with this new one:  Quadratic Lands (virtualhosting.hk) Sent from Mail for Windows From: Kevin OwockiSent: 16 June 2022 00:12To: Developer-piyush/GitquadCc: SubscribedSubject: [Developer-piyush/Gitquad] site is down (Issue #3) http://857tp1qb31bkh1ncp6f3vsbb0s.ingress.provider-0.prod.ams1.akash.pub/ is down—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Developer-piyush** [comment]
The lease is expired…Please replace pinged link with this new one and it will be up again http://5v7umb9mt9asr8vj9fnrqu0t2o.ingress.akash.virtualhosting.hk/ Thank you Sent from Mail for Windows From: Kevin OwockiSent: 16 June 2022 00:12To: Developer-piyush/GitquadCc: SubscribedSubject: [Developer-piyush/Gitquad] site is down (Issue #3) http://857tp1qb31bkh1ncp6f3vsbb0s.ingress.provider-0.prod.ams1.akash.pub/ is down—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Developer-piyush** [comment]
The issue is fixed and site is live again at: http://decentralized.quadraticlands.com/
Thank you🤝
